version: '3.1'

services:
  database:
    build:
      context: ./docker/database
    container_name: database
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"

  nginx:
    build:
      context: ./../
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    build:
      context: ./../
      dockerfile: ./infrastructure/docker/php/Dockerfile
    container_name: php
    restart: always
    volumes:
      - ../:/var/www/html

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger"
    ports:
      - "8082:8080"
    volumes:
      - ./../documentation/:/documentation
    environment:
      SWAGGER_JSON: /documentation/api.yaml

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
