openapi: 3.0.0
info:
  title: Users API
  description: Api to learn about hexagonal and ddd architecture
  version: 0.0.1
servers:
  - url: http://localhost/api/
    description: Local server

paths:
  /api/health-check:
    $ref: "./health-check.yaml"
  /api/user/create:
    $ref: "./User/user-creator.yaml"
